---
- name: Apache server installed
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Apache enabled and running
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started

    - name: Deploy index.html to Apache Server
      ansible.builtin.template:
        src: roles/present/templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '644'
