---
- name: Apache server installed
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: absent
