---
- name: Apache server installed
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: Apache enabled and running
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started
  
    - name: Set facts for web page
      ansible.builtin.set_fact:
        font_color: #ff0000
        short_description: This is a Short Description
        description: This is a Description
        target: pifrox02
        requester: David Ogea
        requested_on: 01.09.2024

    - name: Copy index.html
      ansible.builtin.copy:
        src: roles/present/templates/index.html.j2
        dest: /var/www/html/index.html
        mode: '644'
