---
- name: Apache server uninstalled
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Destroy Apache
      ansible.builtin.apt:
        name: apache2
        state: absent
        purge: true
