---
- name: Apache server installed
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Copy index.html
      ansible.builtin.copy:
        src: web2.html
        dest: /var/www/html/index.html
        mode: '644'