---

- name: Network Getting Started First Playbook
  gather_facts: false
  hosts: all
  tasks:

    - name: Display the config
      ansible.builtin.debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
