# Test we can logon to 'webservers' and execute python with json lib.
# ansible webservers -m ansible.builtin.ping

---
- name: Example from an Ansible Playbook
  ansible.builtin.ping:

- name: Induce an exception to see what happens
  ansible.builtin.ping:
    data: crash