# This YAML is the top-level playbook (or job template) that is called by Servicenow Portal to initialize a new html page on the selected Raspberry Pi server
#
# Example input variables for a local deployment
#
# metadata:
#   request_id: REQ0010001
#   task_id: SCTASK0010001
#   requester: David Ogea
#   requested_on: 29.08.2024
# variables:
#   pi_frox_target: 32f95a5034e72010f877bbf3e74c00d2
#   pi_frox_short_description: This is the content of the Short Description field comming from Servicenow Portal
#   pi_frox_description: This is the content of the Description field comming from Servicenow Portal
#   pi_frox_font_color: #FF0000

---
- name: Update an existing Pi Frox Demonstrator page
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Update the Pi Frox component
    pi.frox.component:
      name: "{{ variables.name | default('Pi Frox Demonstrator') }}"
      sys_id: "{{ variables.pi_Frox_target | default(omit) }}"
      state: present
      variables: "{{ variables | default({}) }}"
      requst_id: "{{ metadata.request_id | default('N/A') }}"
      task_id: "{{ metadata.task_id | default('N/A') }}"
