---
- hosts: localhost #Not sure if this is correct, to be fixed when possible
  gather_facts: false
  become: false
  tasks:
    - name: Print OS info
      ansible.builtin.package:
        name: apache2
        state: present
