---
- name: Apache server installed
  hosts: localhost
  gather_facts: false
  become: true
  become_user: root
  tasks:

    - name: Install Apache
      ansible.builtin.dnf:
        name: apache2

    - name: Apache enabled and running
      ansible.builtin.service:
        name: apache2
        enabled: true
        state: started

    - name: Copy index.html
      ansible.builtin.copy:
        src: web.html
        dest: /var/www/html/index.html
        mode: '644'